microsoft/binskim

src/BinSkim.Rules/RuleConstants.cs
BA2012 should be the do not modify stack protection cookie check.
BA2013 should be the initialize stack protection check.
=> BA2012 and BA2013 are swapped from tool conversion mapping - fix.

.gitignore, BuildAndTest.cmd, src/BinSkim.Driver.FunctionalTests/BaselineTests.cs, src/BinSkim.Driver.FunctionalTests/BaselineTests.ps1, src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/Corrupted_Native_x86_VS2013_Default.exe.sarif, src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/ManagedInteropAssemblyForAtlTestLibrary.dll.sarif, src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/ManagedResourcesOnly.dll.sarif, src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/Managed_x86_VS2013_Wpf.exe.sarif, src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/MixedMode_x64_VS2013_Default.dll.sarif, src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/MixedMode_x64_VS2013_NoPdb.exe.sarif, src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/MixedMode_x86_VS2013_Default.exe.sarif, src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/MixedMode_x86_VS2013_MissingPdb.dll.sarif, src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/Native_x64_VS2013_Default.dll.sarif, src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/Native_x64_VS2015_Default.dll.sarif, src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/Native_x86_VS2013_Default.exe.sarif, src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/Native_x86_VS2013_PdbMissing.exe.sarif, src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/Native_x86_VS2013_ResourceOnly.dll.sarif, src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/Native_x86_VS2015_Default.exe.sarif
They were not being run from BuildAndTest.cmd, but they were running and failing in VS. This fixes the test and enables it on the command line as well.
The baseline had machine, configuration, and runtime-specific strings in it. The fix is to strip them from the baseline on generation and from the actual output during the test run.
Also fix up .gitignore to ignore these files and the .vs/ directory and remove a baseline file that has no actual counterpart.
@michaelcfanning
=> Fix failing BinSkim.Driver.FunctionalTests

src/BinaryParsers/PortableExecutable/PE.cs
@BillyONeal 
Identified by Paul Brookes. This problem doesn't seem to effect most PEs as the MajorImageVersion tends to match the MajorSubsystemVersion. This isn't true for some EFI binaries under analysis, though.
=> Correct retrieval of MajorSubsystemVersion

README.md
No content changes, but I fixed the formatting within the README file and bumped the version link to reflect v1.3.9, which is now available on nuget.org.
=> Update README (formatting and new version on nuget.org).

BuildAndTest.cmd, BuildPackages.cmd
Correct build scripts to provide for both x86 and x64 packages. @EasyRhinoMSFT
=> Provide for x86 and x64 builds

src/BinSkim.Rules/EnableSpectreMitigations.cs, src/BinSkim.Rules/RuleConstants.cs, src/BinSkim.Rules/RuleResources.Designer.cs, src/BinSkim.Rules/RuleResources.resx
@Evmaus-MS @paddymcd-MSFT 
There is a deserialization issue with the new option, will get this fixed in the next commit. Wanted to show the basics of this change. We need a test binary that links a MASM modules
=> Enable reporting of MASM modules

src/BinSkim.Rules/EnableSpectreMitigations.cs
Add support for ARM mitigations comping online in a different build to x8664 compilers
Refactor to make finding the compiler version to a function call to support other Rules reaching in to find the appropriate compiler version
=> Dev/paddymcd msft/real spectre

src/BinSkim.Rules.FunctionalTests/FunctionalTestsData/EnableSpectreMitigations/GenerateTests.ps1, src/BinSkim.Rules.FunctionalTests/FunctionalTestsData/EnableSpectreMitigations/donkey.cpp, src/BinSkim.Rules/EnableSpectreMitigations.cs, src/BinSkim.Rules/RuleResources.Designer.cs, src/BinSkim.Rules/RuleResources.resx
@paddymcd-MSFT here is your change reapplied to current spectre-working. if you see anything that is missing/merged incorrectly, let me know.
@Evmaus-MS
=> Merge Paddy's check for disabling optimizations (/Od) in spectre rule

src/BinSkim.Rules/BuildWithSecureTools.cs, src/BinSkim.Rules/EnableSpectreMitigations.cs, src/BinSkim.Rules/RuleResources.Designer.cs, src/BinSkim.Rules/RuleResources.resx, src/UnitTests.BinSkim.Rules/EnableSpectreMitigationsTests.cs
This replaces the existing configuration model with a slightly more flexible one, largely as we've discussed elsewhere, and provides new unit tests for the various helper methods included in the change.
The XML config for MitigatedCompilers looks like this with this change:
`<Properties Key="MitigatedCompilers" Type="PropertiesDictionary">
<Properties Key="Arm" Type="PropertiesDictionary" />
<Properties Key="X86" Type="PropertiesDictionary">
<Property Key="19.0.*.* - 19.0.*.*" Value="QSpectreAvailable" />
<Property Key="19.10.*.* - 19.10.*.*" Value="QSpectreAvailable" />
<Property Key="19.12.*.* - 19.12.*.*" Value="QSpectreAvailable, D2GuardSpecLoadAvailable" />
<Property Key="19.12.25830.2-19.12.*.*" Value="D2GuardSpecLoadAvailable" />
<Property Key="19.13.*.* - 19.13.*.*" …
=> New Spectre Config Model

src/BinSkim.Driver/BinSkim.Driver.csproj, src/BinSkim.Driver/BinSkim.cs
This fixes the build so that the native dependencies are properly copied.
=> Fixing build to copy correct dependencies

CreateLayoutDirectory.cmd, CreatePackagesFromLayoutDirectory.cmd
We weren't signing the .exe on Windows.  Although my understanding is that the .exe is basically a modified .net core runtime, we should sign it along with BinSkim.dll.
=> Dev/evmaus ms/fix signing layout

src/ReleaseHistory.md
Most (but not all) of the "NuGet Package" links were missing the final `)` so the full URL showed instead of "NuGet Package" being a link.
=> Fix Markdown formatting in ReleaseHistory.md

src/BinSkim.Driver/AnalyzeCommand.cs
Also fixes #2211
The initial creation of this draft PR includes a change to point to a specific commit in sarif-sdk, where the changes from BinSkim were moved.
=> Remove redundant code, now handled in sarif-sdk

src/BinaryParsers/PEBinary/ProgramDatabase/Pdb.cs
```
C:\Path\Humanizer.dll : error ERR998.ExceptionInAnalyze : BA2004 : An exception of type 'UnauthorizedAccessException' was raised analyzing 'Humanizer.dll' for check 'EnableSecureSourceCodeHashing' (which has been disabled). The exception may have resulted from a problem related to parsing the analysis target, and not specific to the rule, however.
UnauthorizedAccessException: Access to the path 'C:\Path' is denied.
at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at System.IO.File.OpenRead(String path)
at …
```
=> Fixing exception when pdb is embedded

.devcontainer/devcontainer.json
- ready-to-start GitHub Codespaces configuration with all necessary tooling
- in addition, it provides basic tools for:
- .NET development
- GitHub support
- overall more pleasant VS Code experience
The configuration consists of:
- `"image":` - a declaration of the Docker image that the Codespace container is created from (this is a list of images and code examples that [work with GitHub Codespaces](https://github.com/microsoft/vscode-dev-containers/tree/main/containers))
- `"mcr.microsoft.com/vscode/devcontainers/dotnet:0.201.9-3.1"` - the Codespace container runs from an Ubuntu 20.04 image with .NET Core SDK installed (`0.201.9` is the latest .NET Core SDK Docker image tagged version)
- `"settings":` - a list of VS Code settings to be applied automatically after the Codespace container …
=> Resolves: Add GitHub Codespaces configuration

src/BinSkim.Rules/PERules/PEBinarySkimmerBase.cs
To avoid null reference exception when accessing PEHeader for a pdb file.
Fixes #419
=> Ignore .pdb files in PEBinarySkimmer

BuildAndTest.cmd
Tried adding prebuild target in csproj file to enlist submodule during visualstudio build (msbuild) but doesn't work.
Looks like vs/msbuild always tries to build referenced projects first and if referenced project files doesn't exist physically the build fails.
=> Add command to restore submodule in BuildAndTest.cmd

src/BinSkim.Driver/AnalysisSummaryExtractor.cs, src/BinSkim.Driver/AnalyzeCommand.cs, src/BinSkim.Sdk/CompilerDataLogger.cs, src/BinSkim.Sdk/ExecutionException.cs
Get ExceptionData from SarifLog Invocations and build exceptions to be sent to AppInsight.
=> Send exceptions data to AppInsight

src/BinSkim.Rules/DwarfRules/BA4002.ReportDwarfCompilerData.cs, src/BinSkim.Rules/PERules/BA4001.ReportPECompilerData.cs, src/BinSkim.Sdk/CompilerData.cs, src/BinSkim.Sdk/CompilerDataLogger.cs, src/ReleaseHistory.md
1. Change compiler report rule to report all modules in file
2. fix bug in the report field position
3. merge 2 similar method to one
=> Change compiler report rule to report all modules in file

src/BinSkim.Driver/AnalysisSummaryExtractor.cs
Adding null reference  check to see if ToolExecutionNotifications in sarif is null.
=> Fix issue sending exception when there is no notification

src/BinSkim.Sdk/CompilerDataLogger.cs
This change will fix the following exception:
```
ArgumentException: String cannot be of zero length. (Parameter 'oldValue')
at System.String.Replace(String oldValue, String newValue)
at Microsoft.CodeAnalysis.IL.Sdk.CompilerDataLogger..ctor(IAnalysisContext analysisContext, IEnumerable`1 targetFileSpecifiers) in D:\a\r1\a\src\BinSkim.Sdk\CompilerDataLogger.cs:line 59
at Microsoft.CodeAnalysis.IL.AnalyzeCommand.CreateContext(AnalyzeOptions options, IAnalysisLogger logger, RuntimeConditions runtimeErrors, PropertiesDictionary policy, String filePath) in D:\a\r1\a\src\BinSkim.Driver\AnalyzeCommand.cs:line 59
at Microsoft.CodeAnalysis.Sarif.Driver.AnalyzeCommandBase`2.DetermineApplicabilityAndAnalyze(TOptions options, IEnumerable`1 skimmers, TContext rootContext, String target, ISet`1 …
```
=> When path is empty do not replace string

src/BinSkim.Rules/PERules/BA4001.ReportPECompilerData.cs, src/BinSkim.Sdk/CompilerData.cs, src/BinSkim.Sdk/CompilerDataLogger.cs, src/BinaryParsers/PEBinary/PortableExecutable/PE.cs, src/Test.UnitTests.BinSkim.Driver/CompilerDataLoggerUnitTests.cs, src/Test.UnitTests.BinSkim.Driver/StubTelemetryChannel.cs
Read assembly references from managed assemblies and send to telemetry by chunks.
=> Send assembly references to Telemetry

src/BinSkim.Sdk/CompilerDataLogger.cs, src/BinSkim.Sdk/Properties/AssemblyInfo.cs, src/NuGet.Config, src/Shared/SharedAssemblyInfo.cs, src/Test.UnitTests.BinSkim.Driver/CompilerDataLoggerUnitTests.cs
When we changed from single thread to multi-thread application, the reporting rule started to behave differently:
- many configurations were being created
- many sessions were being created
- hash wasn't showing correctly since the hash isn't calculated previously
This PR will fix the following issues:
- session/telemetry objects should not be overridden if already exists
- session/telemetry objects should be created only once (even in a multithread environment)
- hash should have a reference to the context since it will be only created once we start loading a specific file
=> Create one session/telemetry configuration per run

src/Test.UnitTests.BinSkim.Driver/AnalysisSummaryExtractorUnitTests.cs
FluentAssertions auto upgrade by dependabot, 
new version has a minor change that does not allow to use Should().Equals()
it need to use methods in the class like:
Should().Be
Should().BeEquivalentTo
We only have 1 test method using it, changed to use Be() which is a exact match, base on the code logic.
=> FluentAssertions test code minor syntax change

src/BinSkim.Driver/AnalyzeCommand.cs, src/ReleaseHistory.md, src/Test.FunctionalTests.BinSkim.Driver/AnalyzeCommandTest.cs, src/Test.FunctionalTests.BinSkim.Driver/AnalyzeCommandTests.cs, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Binskim.empty.v1.0.0.sarif, src/Test.FunctionalTests.BinSkim.Driver/Test.FunctionalTests.BinSkim.Driver.csproj
Today, the guardian task always outputs the SARIF to v1.0.0 and our code wasn't prepared to read that, throwing the `JsonSerializationException` exception.
This change will verify what is the version that the user is exporting and will read based on that.
=> Fix `JsonSerializationException' that occurs when saving SARIF v1 with telemetry enabled.

docs/RulesAndErrorsTroubleshootingGuide.md
This change will fix the image extension that we are using in the markdown files.
The link bellow will allow you to see how it will appear:
https://github.com/microsoft/binskim/blob/959172f554bd89e763fd88c396c655a810676f9d/docs/RulesAndErrorsTroubleshootingGuide.md
=> Fixing image links

src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Binskim.linux-x64.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Binskim.win-x64.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Binskim.win-x86.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Corrupted_Native_x86_VS2013_Default.exe.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/ManagedInteropAssemblyForAtlTestLibrary.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/ManagedResourcesOnly.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Managed_x64_VS2019_CSharp_DebugType_None.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Managed_x64_VS2019_VB_DebugType_None.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/MixedMode_x64_VS2013_NoPdb.exe.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/MixedMode_x64_VS2019_CPlusPlus_DEBUG_NONE.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/MixedMode_x86_VS2013_MissingPdb.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Native_ARM_VS2015_CvtresResourceOnly.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Native_x64_VS2015_CvtresResourceOnly.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Native_x64_VS2019_Atl_NoPdbGenerated.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Native_x64_VS2019_CPlusPlus_DEBUG_NONE.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Native_x86_VS2013_PdbMissing.exe.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Native_x86_VS2015_CvtresResourceOnly.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Native_x86_VS2017_15.5.4_PdbStripped.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Uwp_ARM_VS2015_DefaultBlankApp.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Uwp_ARM_VS2015_DefaultBlankApp.exe.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Uwp_x64_VS2015_DefaultBlankApp.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Uwp_x64_VS2015_DefaultBlankApp.exe.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Uwp_x86_VS2015_DefaultBlankApp.dll.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Uwp_x86_VS2015_DefaultBlankApp.exe.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/clang.stack_protector.a.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/gcc.pe.objectivec.dwarf.exe.sarif, src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/gcc.stack_protector.a.sarif
In the previous [PR](https://github.com/microsoft/binskim/pull/555), we saw an issue where toolNotifications with artifactLocations were not updating artifacts.
This change will fix that and make the proper link between notifications -> artifactLocation -> artifacts.
We will see files where we are adding back the artifacts and updating the index if the artifacts exists.
=> Fix `SarifLogger` artifacts generation when logging notifications

src/BinSkim.Driver/MultithreadedAnalyzeCommand.cs, src/Test.UnitTests.BinSkim.Driver/MultithreadedAnalyzeCommandTests.cs
In this change, I'm improving how the method `ReturnCommonPathRootFromTargetSpecifiersIfOneExists` generates the common path. The method will now generate the common path from the target specifiers if that exists.
The current behavior will generate the following:
```
c:\path1\ C:\path2\ -> no common path
c:\path1\ C:\path1\path2\ -> no common path
c:\path1\ C:\path1\path2\1.exe -> no common path
```
The new behavior will generate the following:
```
c:\path1\ c:\path2\ -> C:\
c:\path1\ c:\path1\path2\ -> c:\path1\
c:\path1\ c:\path1\path2\1.exe -> c:\path1\
```
The following tests were added:
- Shuffling the array to guarantee that won't matter the order of the input
- UNC examples
- Paths with `..`
- Paths with duplicated information
- Paths that point to files and folders
- Paths with …
=> Improving common path function

src/BinSkim.Rules/PERules/BA2006.BuildWithSecureTools.cs, src/ReleaseHistory.md
User reported issue by email:
new issue with Binskim 1.9.2
```
2022-02-10T15:55:59.5540580Z [Standard]   D:\a\_work\1\a\OpenSSH-Win64\sftp.exe : error ERR998.ExceptionInAnalyze : BA2006 : An exception of type 'KeyNotFoundException' was raised analyzing 'sftp.exe' for check 'BuildWithSecureTools' (which has been disabled). The exception may have resulted from a problem related to parsing the analysis target, and not specific to the rule, however.
2022-02-10T15:55:59.5542301Z [Standard]   KeyNotFoundException: The given key 'C' was not present in the dictionary.
2022-02-10T15:55:59.5543351Z [Standard]      at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
2022-02-10T15:55:59.5544773Z [Standard]      at …
```
=> BUGFIX: Fix missing item in MinimumToolVersionsMap when user only overwrite part of the settings

.github/workflows/codeql-analysis.yml
Dependabot does not have access to "push" and it fails some actions.
With that in mind, the known way to fix this is to disable Dependabot branches from the analysis:
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow#error-403-resource-not-accessible-by-integration-when-using-dependabot
=> Updating CodeQL analysis for Dependabot on push

src/BinaryParsers/ElfBinary/Dwarf/DwarfCompilationUnit.cs, src/BinaryParsers/MachOBinary/SingleMachOBinary.cs, src/BinaryParsers/PEBinary/PortableExecutable/SafePointer.cs
CodeQL reports "This cast is redundant because the expression already has type"
remove the redundant cast
There is No tests added because there is no behavioral implications of this specific type of  change "cast is redundant".
=> CodeQL Fix "This cast is redundant because the expression already has type"

src/BinaryParsers/PEBinary/ProgramDatabase/LinkerCommandLine.cs, src/BinaryParsers/PEBinary/ProgramDatabase/ObjectModuleDetails.cs
Closes #675
This is a mistake in the new `LinkerCommandLine` extractor that I recently added to support performance rules.  Our learnings about case (in)sensitivity and both `/out` and `-out` being equivalent was not applied to ObjectModuleDetails.cs.  As a result it is not possible to isolate the linker command line arguments for certain binaries.
The fix is to make these comparisons case-insensitive and to check for both - and /.
=> LinkerCommandLine fails to populate in some cases due to case sensitivity

src/BinaryParsers/PEBinary/ProgramDatabase/ObjectModuleDetails.cs
The **linker** command line was not used in any rules and it is hidden as a private field.
Now I have a new internal rule need to use it, so exposing this field the same way as **compiler** command line, 2 lines above.
Did not add release history because not impacting user.
=> Expose linker command line

ado-build.yml
New change from GitHub image, the latest now `22.04`, was `20.04`.
`22.04` image only have .NET 6 installed.
Change back to use `20.04`.
https://github.com/actions/runner-images/issues/6399
=> BinSkim - Fix Ubuntu test pipeline

BuildAndTest.sh
Linux test has been randomly success and fail, only starting these few days.
We have no related changes, wondering if there is new VM image testing.
The error is the test is randomly looking for AnyCpu and x64 folder of the dll and can not find it when it thinks AnyCpu is the one to look for.
(note: dotnet test ignores /p:platform so that is not the way to fix this)
The fix simply: Build as x64 and test x64 dll by specify path.
Test: have run the branch build 10 times all success. while main mostly fails.
=> Fix Linux test issue

src/BinSkim.Driver/MultithreadedAnalyzeCommand.cs, src/ReleaseHistory.md, src/Test.FunctionalTests.BinSkim.Driver/AnalyzeCommandTests.cs
Before this change, when no Target file is specified for BinSkim analyze, BinSkim will fail with no clue to users (as shown below)
The change is to check whether Target file is specified at the very beginning of running the analyze command. If target file is not specified, throw an exception with clear message.
After the change, when no target file is specified for BinSkim analyze, BinSkim will fail with clear clue (as shown below).
Add/Modify the test cases.
=> BugFix assertion failed with no clue when TargetFileSpecifiers is null or empty for BinSkim analyze

src/BinaryParsers/ElfBinary/ElfBinary.cs
Lazily load various DWARF things. This will push parsing exceptions into the various rules that first access (and therefore trigger) the parsing problem.
This also prevents over-eager loading of data that rules don't even inspect currently (as was happening with debug line information). This will reduce analysis time and memory pressure.
@shaopeng-gh, my apologies, I didn't see your PR yesterday. Can we review this and check it in and then you can reapply your debug symbols improvement (which looks necessary for complete lazy loading of that code path).
@suvamM
=> Lazily load DWARF data.

BuildAndTest.sh
This is for the public BinSkim, where the existing Linux script does not check out the submodules.
PS. There are already similar scripts in BuildAndTest.cmd to check out submodules. The logic is same.
=> Fix for BuildAndTest.sh for public BinSkim

src/BinSkim.Driver/BinSkim.cs, src/BinSkim.Driver/MultithreadedAnalyzeCommand.cs, src/BinSkim.Driver/RuleTelemetryLogger.cs, src/BinSkim.Sdk/CompilerDataLogger.cs, src/BinSkim.Sdk/Telemetry.cs, src/Test.FunctionalTests.BinSkim.Driver/BaselineTests.cs, src/Test.UnitTests.BinSkim.Driver/CompilerDataLoggerTests.cs, src/Test.UnitTests.BinSkim.Driver/TelemetryTests.cs
Addresses #785
Move App Insights telemetry out of CompilerDataLogger into its own Telemetry class Add support for connection string via BinskimAppInsightsConnectionString environment variable. Put the session ID in the global context instead of individual events. Use a more compact session ID format.
Log OS and tool version.
Log rule summary data.
=> Telemetry enhancements

BuildAndTest.cmd, src/BinSkim.sln, src/Test.ConcurrencyTests/BasicCoyoteTests.cs, src/Test.ConcurrencyTests/Test.ConcurrencyTests.csproj, src/Test.ConcurrencyTests/rewrite.coyote.Windows.Debug.json, src/Test.ConcurrencyTests/rewrite.coyote.Windows.Release.json, src/Test.ConcurrencyTests/rewriteUnitTests.ps1
This PR makes the following changes:
1. Adds a new project with [Coyote testing](https://microsoft.github.io/coyote/#) enabled. The project uses the standard `MSTest` framework to wrap the Coyote tests.
_Note 1_: Coyote_ is a sophisticated controlled concurrency testing framework from Microsoft Research, which can uncover deep concurrency bugs.
_Note 2_: The output path for this new project is kept separate from the general build output folder (`bld\bin`). Coyote requires instrumenting the binaries, and we do not want to instrument production binaries.
2. The PR adds a post-build task to the new project, which performs a dll instrumentation step after the build. The instrumentation is required for controlling the concurrency.
3. The PR adds a simple concurrency unit test where the bug is …
=> Adding Coyote testing support

README.md
RuleContributions.md is important to read, 
most people will not open the doc folder and open each one of the file to see which one meets the need, 
so it is important to link to in the home page of our repo.
=> Effectively expose RuleContributions.md for developers

docs/BinSkimRules.md, src/BinSkim.Rules/RuleResources.Designer.cs, src/BinSkim.Rules/RuleResources.resx
1. Fix BA2025_EnableShadowStack_Description missing the ending period.
2. Fix md file missing update 1 string.
=> Fix BA2025_EnableShadowStack_Description missing the ending period.

README.md, docs/UserGuide.md, src/BinSkim.Driver/AnalyzeOptions.cs
For Linux, need escape semicolon with backslash, else it will be considered another command.
This is the part in BinSkim. The other part is in SARIF SDK https://github.com/microsoft/sarif-sdk/pull/2665
=> Add "(escape semicolon with backslash in Unix-like OS)"

ReleaseHistory.md, src/BinSkim.Driver/BinSkim.Driver.csproj, src/BinSkim.Rules/BinSkim.Rules.csproj, src/BinSkim.Sdk/BinSkim.Sdk.csproj, src/BinaryParsers/BinaryParsers.csproj, src/Test.FunctionalTests.BinSkim.Driver/Test.FunctionalTests.BinSkim.Driver.csproj, src/Test.FunctionalTests.BinSkim.Rules/Test.FunctionalTests.BinSkim.Rules.csproj, src/Test.UnitTests.BinSkim.Driver/Test.UnitTests.BinSkim.Driver.csproj, src/Test.UnitTests.BinSkim.Rules/Test.UnitTests.BinSkim.Rules.csproj, src/Test.UnitTests.BinaryParsers/Test.UnitTests.BinaryParsers.csproj, src/build.common.props
There is a new version of the Microsoft.CodeAnalysis.NetAnalyzers package available (7.0.1)
Warnings were being generated that a new version of the NetAnalyzers were availble.
This PR will update all of the package references to the new version 7.0.1
=> Update Microsoft.CodeAnalysis.NetAnalyzers 7.0.0 --> 7.0.1

README.md, ReleaseHistory.md, docs/UserGuide.md, src/BinSkim.Driver/AnalyzeOptions.cs, src/BinSkim.Driver/MultithreadedAnalyzeCommand.cs, src/Test.FunctionalTests.BinSkim.Driver/AnalyzeCommandTests.cs, src/Test.FunctionalTests.BinSkim.Driver/BaselineTests.cs
Found a bug In 4.1.0 , if `--trace` is provided will have unhandled exception.
The reason is new new pipeline change has SDK traces changed to trace, because we overwrite in BinSkim, we need to change the name ass well.
This is the full error:
=> Fix 4.1.0 issue: `System.InvalidOperationException`: `Sequence contains more than one matching element` when `--trace` is provided

README.md, docs/UserGuide.md
Providing the right examples for user.
See https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/advanced-symsrv-use for syntax information.
=> Fix `sympath` documentation

ReleaseHistory.md, src/BinSkim.Driver/AnalyzeOptions.cs, src/BinSkim.Driver/MultithreadedAnalyzeCommand.cs, src/Test.FunctionalTests.BinSkim.Driver/AnalyzeCommandTests.cs, src/Test.FunctionalTests.BinSkim.Driver/Test.FunctionalTests.BinSkim.Driver.csproj
As Requested, will not throw error on `--hashes` and `--statistics`.
I checked 1.9.5 and also 1.9.2, `--statistics` have no references so the functionality should be removed sometime back.
`--statistics` is restored to be the same as 1.9.5, no effect but will not throw error.
=> Restore command-line option `--hashes` and `--statistics`

src/BinSkim.Rules/PERules/BA2004.EnableSecureSourceCodeHashing.cs
when all error are caused by no hash, the current code will also generate an error with no item in the list.
generate an error will cause pipeline to fail, so we should fix it.
=> Fix BA2004 bug creating error with empty list

README.md, docs/UserGuide.md
For user reported issue.
`http` will not work on some environments, we should not have it as sample.
=> Fix Symbol path example from using `http` to `https`

ReleaseHistory.md, src/BinSkim.Driver/BinSkim.cs
Issue found by Michael.
`--recurse` not working without explicitly adding true.
SPM already had similar fix, we just re-use it.
=> * BUG: Fix `--quiet`, `--recurse`, `--rich-return-code`, `--ignorePdbLoadError` and `--environment` not working without explicitly adding `true`.

ReleaseHistory.md, src/BinSkim.Rules/DwarfRules/BA4002.ReportElfOrMachoCompilerData.cs, src/BinSkim.Sdk/CompilerDataLogger.cs, src/Test.UnitTests.BinSkim.Driver/TelemetryTests.cs
* NEW: `BA4002.ReportElfOrMachoCompilerData`, which collects telemetry data for Elf and Macho files, is now enabled by default.
Also, to make sure the `--disable-telemetry` not just disable the telemetry collection to server,
but local CSV as well per Michael comment:
"we need to honor the --disable-telemetryflag. i.e., if people set this flag, turn off that data generation."
=> `BA4002.ReportElfOrMachoCompilerData` enabled by default

src/BinSkim.Rules/RuleResources.Designer.cs, src/BinSkim.Rules/RuleResources.resx
Adding VC project properties info to suggestions
Making long strings multiline for easier reading.
Adding more info for BA2004 and clarifying some suggestions for compiler defaults.
=> Adding VC project properties info to 'how to resolve' suggestions.

.github/workflows/codeql-analysis.yml, .github/workflows/dotnet-format.yml, .gitmodules, BuildAndTest.cmd, BuildAndTest.sh, ReleaseHistory.md, ado-build.yml, global.json, src/BinSkim.Driver/BinSkim.Driver.csproj, src/BinSkim.Rules/BinSkim.Rules.csproj, src/BinSkim.Sdk/BinSkim.Sdk.csproj, src/BinSkim.Sdk/Telemetry.cs, src/BinSkim.sln, src/BinaryParsers/BinaryParsers.csproj, src/BinaryParsers/PEBinary/ProgramDatabase/Pdb.cs, src/BinaryParsers/VersionConstants.cs, src/Directory.Packages.props, src/Nuget/BinSkim.nuspec, src/Shared/SharedAssemblyInfo.cs, src/Test.FunctionalTests.BinSkim.Driver/Test.FunctionalTests.BinSkim.Driver.csproj, src/Test.FunctionalTests.BinSkim.Rules/Test.FunctionalTests.BinSkim.Rules.csproj, src/Test.UnitTests.BinSkim.Driver/Test.UnitTests.BinSkim.Driver.csproj, src/Test.UnitTests.BinSkim.Rules/Test.UnitTests.BinSkim.Rules.csproj, src/Test.UnitTests.BinaryParsers/Test.UnitTests.BinaryParsers.csproj
This pull request aims to migrate the BinSkim project from using the sarif-sdk submodule to a NuGet package. This change is intended to streamline the dependency management process and improve build reliability.
Removed the sarif-sdk submodule.
Added the sarif-sdk NuGet package to the project.
Updated the project files to reference the NuGet package instead of the submodule.
Simplified Dependency Management: Using NuGet packages simplifies the process of managing dependencies, making it easier to update and maintain them.
Improved Build Reliability: By moving away from submodules, we reduce the potential for errors related to submodule synchronization and updates.
Verified that the project builds successfully with the new NuGet package.
Ran all existing tests to ensure no regressions were …
=> Replace sarif-sdk submodule with Nuget package

.github/workflows/codeql-analysis.yml, BuildAndTest.cmd
Removal of sarif-sdk folder. Folder is causing issue in Azure Pipelines when checkout of the repository is happening.
=> Remove sarif-sdk subproject folder and update dotnet-format tool version

ReleaseHistory.md, src/BinSkim.Driver/AnalyzeOptions.cs, src/BinSkim.Driver/MultithreadedAnalyzeCommand.cs, src/BinSkim.Rules/PERules/PEBinarySkimmerBase.cs, src/BinSkim.Rules/RuleResources.Designer.cs, src/BinSkim.Rules/RuleResources.resx, src/BinSkim.Sdk/BinaryAnalyzerContext.cs, src/BinaryParsers/BinaryParsersProperties.cs, src/Test.FunctionalTests.BinSkim.Driver/AnalyzeCommandTests.cs
The error ERR998.ExceptionInCanAnalyze occurs when BinSkim attempts to determine if 'netfile.exe' is a valid analysis target for the `'EnableControlFlowGuard'` check. The exception is caused by an `InvalidOperationException` related to RVA not belonging to any section. We want to not break the build but proceed instead and control breaking based on the Sarif logs.
The error can be reproduced by running BinSkim analysis for `'netfile.exe'` stored in TestData or similar files. Which cannot be easily read by PEReader.
Update BinSkim to handle exceptions during the analysis process without breaking the build. This includes proceeding with the analysis even if a file cannot be read or analyzed properly. 
The fix should apply to all occurrences of ERR998.ExceptionInCanAnalyze. The release of …
=> Implement new ignore setting when PE file cannot be analyzed

src/BinSkim.Driver/BinSkim.cs, src/BinSkim.Driver/ExpandArguments.cs, src/Test.UnitTests.BinSkim.Driver/ExpandArgumentsUnitTests.cs
Unwrapping/expanding .rsp files used to be supported on Windows only due to FFI calling to `shell32.dll`. This PR removes FFI in favor of a code native solution.
the `sarif-sdk` submodule contains a reimplementation of `CommandLineToArgvW`. Rather than updating `sarif-sdk`, we've moved the relevant code into the BinSkim codebase, and pointed to the reimplementation instead to slightly lessen our reliance on `sarif-sdk`, while simultaneously increasing our supported platforms.
Alongside this change, tests were ported and altered over into the BinSkim codebase.
=> Cross-Platform .rsp File Support

BuildAndTest.cmd, BuildPackages.cmd, ado-build.yml, src/BinSkim.Driver/BinSkim.Driver.csproj
This pull request includes several changes to the build and publish processes in the `BuildAndTest.cmd`, `BuildPackages.cmd`, and `BinSkim.Driver.csproj` files. The changes primarily focus on improving the build configuration, updating paths, and ensuring the application is self-contained and ready to run.
Improvements to build and publish processes:
* [`BuildAndTest.cmd`](diffhunk://#diff-a17fe36ab1b8b2ea4b8558b6310714ae6a031a2c138374e6f1d4d7335b9c071bL49-R49): Removed the `--no-restore` flag from the `dotnet build` command to simplify the build process.
* [`BuildAndTest.cmd`](diffhunk://#diff-a17fe36ab1b8b2ea4b8558b6310714ae6a031a2c138374e6f1d4d7335b9c071bL80-R80): Updated the path for the `BinSkim.exe` export rules to ensure it points to the correct publish directory.
* …
=> Adding possibility for SelfContained and R2R Publish

src/Test.UnitTests.BinSkim.Driver/AnalysisSummaryExtractorUnitTests.cs
This commit introduces a new method to prepare environment variables for the `AnalysisSummary` object in the `ExtractAnalysisSummary_WithoutBuildPipelineInfo` test. It initializes a list of tuples with build and repository-related variable names set to `null`, ensuring that the `UpdateBuildPipelineInfo` method can be tested in a clean state. This allows for verification that the summary fields remain null or empty as expected.
=> Add environment variable preparation in unit test
