microsoft/binskim

- src/BinSkim.Driver/BinSkim.Driver.csproj
- src/BinSkim.Driver/packages.config
- src/BinSkim.Rules.FunctionalTests/BinSkim.Rules.FunctionalTests.csproj
- src/BinSkim.Rules.FunctionalTests/packages.config
@michaelcfanning 
The build was broken in VS 2015 Update 1 RTM (analyzer exception) without this.
> Update to latest stable Roslyn packages

- BuildAndTest.cmd
- src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/Corrupted_Native_x86_VS2013_Default.exe.sarif
- src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/ManagedInteropAssemblyForAtlTestLibrary.dll.sarif
- src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/ManagedResourcesOnly.dll.sarif
- src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/Managed_x86_VS2013_Wpf.exe.sarif
- src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/MixedMode_x64_VS2013_Default.dll.sarif
- src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/MixedMode_x64_VS2013_NoPdb.exe.sarif
- src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/MixedMode_x86_VS2013_Default.exe.sarif
- src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/MixedMode_x86_VS2013_MissingPdb.dll.sarif
- src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/Native_x64_VS2013_Default.dll.sarif
- src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/Native_x64_VS2015_Default.dll.sarif
- src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/Native_x86_VS2013_Default.exe.sarif
- src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/Native_x86_VS2013_PdbMissing.exe.sarif
- src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/Native_x86_VS2013_ResourceOnly.dll.sarif
- src/BinSkim.Driver.FunctionalTests/BaselineTestsData/Expected/Native_x86_VS2015_Default.exe.sarif
- src/BinSkim.Rules.FunctionalTests/RuleTests.cs
- src/BinSkim.Rules/BinSkim.Rules.csproj
- src/BinSkim.Rules/NativeInterop.cs
- src/BinSkim.Rules/RuleResources.Designer.cs
- src/BinSkim.Rules/RuleResources.resx
- src/BinSkim.Rules/SignSecurely.cs
- src/BinaryParsers/VersionConstants.cs
@nguerrera @BillyONeal @lgolding @tikiwanMS @bobschumaker @davidknise
> Update signing rule. Update version to 1.2.16

- src/BinaryParsers/PortableExecutable/PE.cs
> Capture SRM exceptions in TargetLoad member.

- src/BinSkim.Rules/RuleResources.Designer.cs
- src/BinSkim.Rules/RuleResources.resx
- src/BinSkim.Rules/RulesExtensionMethods.cs
@nguerrera @BillyONeal @lgolding @rtaket
> Update signing rule output to include descriptive text.

- BuildAndTest.cmd
- src/BinSkim.Driver.FunctionalTests/BinSkim.Driver.FunctionalTests.csproj
- src/BinSkim.Driver/BinSkim.Driver.csproj
- src/BinSkim.Rules.FunctionalTests/BinSkim.Rules.FunctionalTests.csproj
- src/BinSkim.Rules/BinSkim.Rules.csproj
- src/BinSkim.Sdk/BinSkim.Sdk.csproj
- src/BinaryParsers/BinaryParsers.csproj
- src/BinaryParsers/VersionConstants.cs
- src/Binskim.targets
- src/ReleaseHistory.md
- src/build.props
@BillyONeal @Evmaus-MS @rtaket
> Build target

- src/BinSkim.Driver/AnalyzeCommand.cs
- src/BinSkim.Driver/RoslynAnalyzer/ILDiagnosticsAnalyzer.cs
- src/BinSkim.Rules/BuildWithSecureTools.cs
- src/BinSkim.Rules/EnableControlFlowGuard.cs
- src/BinSkim.Rules/EnableHighEntropyVirtualAddresses.cs
- src/BinSkim.Rules/LoadImagesAboveFourGigabyteAddress.cs
- src/BinSkim.Rules/RulesExtensionMethods.cs
- src/BinaryParsers/PortableExecutable/ImageFieldData.cs
- src/BinaryParsers/PortableExecutable/ImageHeader.cs
- src/BinaryParsers/PortableExecutable/PE.cs
- src/BinaryParsers/PortableExecutable/PEExtensionMethods.cs
- src/BinaryParsers/PortableExecutable/SafePointer.cs
- src/BinaryParsers/ProgramDatabase/Symbol.cs
> Resolve various issues identified by Semmle analysis

- README.md
- docs/UserGuide.md
as promised during the call today, I have converted the user guide from the word doc as markdown and am now submitting a PR (along with a few grammatical changes). Once this is up, we can further contribute, clean up further and make it even better.
> Updated user guide to include steps from doc

- src/BinSkim.Driver.FunctionalTests/BaselineTests.cs
- src/BinSkim.Driver.FunctionalTests/BinSkim.Driver.FunctionalTests.csproj
- src/BinSkim.Driver.FunctionalTests/packages.config
- src/BinSkim.Driver/BinSkim.Driver.csproj
- src/BinSkim.Driver/packages.config
- src/BinSkim.Rules.FunctionalTests/BinSkim.Rules.FunctionalTests.csproj
- src/BinSkim.Rules.FunctionalTests/packages.config
- src/BinSkim.Rules/BinSkim.Rules.csproj
- src/BinSkim.Rules/packages.config
- src/BinSkim.Sdk/BinSkim.Sdk.csproj
- src/BinSkim.Sdk/packages.config
- src/BinaryParsers/BinaryParsers.csproj
- src/BinaryParsers/packages.config
- src/Nuget/BinSkim.nuspec
- src/build.props
> Update SARIF dependencies to 1.7.1

- BuildAndTest.cmd
- BuildPackages.cmd
- src/BinSkim.Driver.FunctionalTests/BaselineTests.cs
- src/Nuget/BinSkim.nuspec
- src/build.props
@EasyRhinoMSFT @Evmaus-MS 
fyi, we now flatten output to a single directory. this work in preparation for releasing a signed 1.4.4.
> Flatten build output and prepare for code signing

- src/BinSkim.Rules/EnableSpectreMitigations.cs
- src/BinSkim.Rules/RuleConstants.cs
@paddymcd-MSFT 
fyi, merging simple rename of rule and moved some helper types about a bit. I have a small list of suggestions on implementation, will provide offline. this check is looking good.
> Rule rename

- src/BinSkim.Rules/BinSkim.Rules.csproj
- src/BinSkim.Rules/EnableSpectreMitigations.cs
- src/BinaryParsers/ProgramDatabase/CompilerCommandLine.cs
Merging spectre work back into refinements branch
> Dev/paddymcd msft/jan2018 check secure code gen

- src/BinSkim.Rules/EnableSpectreMitigations.cs
> Provide serialization for compiler mitigation data

- src/BinSkim.Rules/PERules/BA2015.EnableHighEntropyVirtualAddresses.cs
- src/BinSkim.Rules/RuleResources.Designer.cs
- src/BinSkim.Rules/RuleResources.resx
Bug fixes for:
https://github.com/Microsoft/binskim/issues/167
https://github.com/Microsoft/binskim/issues/169
> Some fixes for bugs pre-1.5.0.

- CreatePackagesFromLayoutDirectory.cmd
Adds a script to create NuGet packages from the signing directory.
> Add CreatePackagesFromLayoutDirectory script.

- README.md
> Release note update

- src/BinaryParsers/PEBinary/PortableExecutable/PE.cs
@BillyONeal your prior PR feedback was not in vain.
> Small change reflecting PR feedback from previous wix noise reduction

- docs/UserGuide.md
Fix some wrong example command lines in user guide for running binskim.exe to avoid confusion for users.
> fix user guide example

- src/.editorconfig
- src/BinSkim.Rules/PERules/BA2002.DoNotIncorporateVulnerableDependencies.cs
- src/BinSkim.Rules/PERules/BA2005.DoNotShipVulnerableBinaries.cs
- src/BinSkim.Rules/PERules/BA2006.BuildWithSecureTools.cs
- src/BinSkim.Rules/PERules/BA2007.EnableCriticalCompilerWarnings.cs
- src/BinSkim.Rules/PERules/BA2008.EnableControlFlowGuard.cs
- src/BinSkim.Rules/PERules/BA2014.DoNotDisableStackProtectionForFunctions.cs
- src/BinSkim.Rules/PERules/BA2024.EnableSpectreMitigations.cs
- src/BinSkim.Rules/ReproInformationConfiguration.cs
- src/BinSkim.Rules/VulnerableDependencyDescriptor.cs
- src/Test.FunctionalTests.BinSkim.Rules/RoslynAnalysisContextTests.cs
- src/Test.FunctionalTests.BinSkim.Rules/RoslynCompilationStartAnalysisContextTests.cs
- src/Test.FunctionalTests.BinSkim.Rules/TestRoslynAnalyzer.cs
@chinarosesz 
Little bit of tail from your recent and fantastic reformatting infrastructure work.
> Formatting clean-up changes after last work.

- .gitignore
- BuildAndTest.cmd
- CreateLayoutDirectory.cmd
- CreatePackagesFromLayoutDirectory.cmd
- src/BinSkim.Driver/BinSkim.Driver.csproj
- src/ReleaseHistory.md
- src/build.netcore.props
Related to #261. Generally refreshing BinSkim compatibility with *nix environments.
> Update to dotnet 3.1.

- src/BinSkim.Rules/BinScopeCompatibility.cs
- src/BinSkim.Rules/PERules/BA2001.LoadImagesAboveFourGigabyteAddress.cs
- src/BinSkim.Rules/PERules/BA2002.DoNotIncorporateVulnerableDependencies.cs
- src/BinSkim.Rules/PERules/BA2005.DoNotShipVulnerableBinaries.cs
- src/BinSkim.Rules/PERules/BA2006.BuildWithSecureTools.cs
- src/BinSkim.Rules/PERules/BA2007.EnableCriticalCompilerWarnings.cs
- src/BinSkim.Rules/PERules/BA2008.EnableControlFlowGuard.cs
- src/BinSkim.Rules/PERules/BA2009.EnableAddressSpaceLayoutRandomization.cs
- src/BinSkim.Rules/PERules/BA2010.DoNotMarkImportsSectionAsExecutable.cs
- src/BinSkim.Rules/PERules/BA2011.EnableStackProtection.cs
- src/BinSkim.Rules/PERules/BA2012.DoNotModifyStackProtectionCookie.cs
- src/BinSkim.Rules/PERules/BA2013.InitializeStackProtection.cs
- src/BinSkim.Rules/PERules/BA2014.DoNotDisableStackProtectionForFunctions.cs
- src/BinSkim.Rules/PERules/BA2015.EnableHighEntropyVirtualAddresses.cs
- src/BinSkim.Rules/PERules/BA2016.MarkImageAsNXCompatible.cs
- src/BinSkim.Rules/PERules/BA2018.EnableSafeSEH.cs
- src/BinSkim.Rules/PERules/BA2019.DoNotMarkWritableSectionsAsShared.cs
- src/BinSkim.Rules/PERules/BA2021.DoNotMarkWritableSectionsAsExecutable.cs
- src/BinSkim.Rules/RuleConstants.cs
Simple file/identifier renames.
> Update rule id constant names and containing source file.

- src/BinSkim.Driver/AnalyzeCommand.cs
> Settng default output to Current

- ado-build.yml
> Adding linux job

- src/BinSkim.Driver/BinSkim.cs
> Fixing $LastExitCode for help and version commands

- BuildAndTest.cmd
- BuildPackages.cmd
- CreateLayoutDirectory.cmd
- CreatePackagesFromLayoutDirectory.cmd
- ado-build.yml
- src/BinSkim.Driver/BinSkim.Driver.csproj
- src/BinSkim.Driver/DotnetToolSettings.xml
- src/Nuget/BinSkim.nuspec
- src/ReleaseHistory.md
Fixes #305 
- Changing from self-contained package to dotnet tool package (100MB -> 8MB size)
- Improving script to test all projects passing solution
- Fixing signing script
> Converting to dotnet tool

- .gitmodules
- ado-build.yml
- src/BinSkim.Driver/AnalyzeCommand.cs
- src/BinSkim.Driver/AnalyzeOptions.cs
- src/BinSkim.Driver/BinSkim.Driver.csproj
- src/BinSkim.Rules/BinSkim.Rules.csproj
- src/BinSkim.Rules/BinarySkimmer.cs
- src/BinSkim.Sdk/BinSkim.Sdk.csproj
- src/BinSkim.Sdk/BinaryAnalyzerContext.cs
- src/BinSkim.sln
- src/BinaryParsers/BinaryParsers.csproj
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTests.cs
- src/Test.FunctionalTests.BinSkim.Driver/Test.FunctionalTests.BinSkim.Driver.csproj
- src/Test.FunctionalTests.BinSkim.Rules/Test.FunctionalTests.BinSkim.Rules.csproj
- src/Test.UnitTests.BinSkim.Driver/Test.UnitTests.BinSkim.Driver.csproj
- src/Test.UnitTests.BinSkim.Rules/Test.UnitTests.BinSkim.Rules.csproj
> adding sarif sdk submodule

- src/BinSkim.Driver/AnalyzeCommand.cs
- src/BinSkim.Driver/AnalyzeOptions.cs
- src/BinaryParsers/PEBinary/PortableExecutable/PE.cs
- src/Test.FunctionalTests.BinSkim.Rules/RuleTests.cs
- src/Test.FunctionalTests.BinSkim.Rules/Test.FunctionalTests.BinSkim.Rules.csproj
- src/Test.FunctionalTests.BinSkim.Rules/TestMessageLogger.cs
> Loosen visibility on various things.

- src/BinSkim.Driver/DumpCommand.cs
- src/BinSkim.Rules/PERules/WindowsBinaryAndPdbSkimmerBase.cs
- src/BinaryParsers/PEBinary/ProgramDatabase/PdbException.cs
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTestsData/Expected/Native_x86_VS2017_15.5.4_PdbStripped.dll.sarif
> Display error message instead of E_PDB_MAX

- src/BinSkim.Driver/AnalysisSummaryExtractor.cs
- src/BinSkim.Sdk/AnalysisSummary.cs
- src/BinSkim.Sdk/CompilerDataLogger.cs
- src/Test.UnitTests.BinSkim.Driver/AnalysisSummaryExtractorUnitTests.cs
As mentioned in this page https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops, we can read the pre-defined variables from environment variables.
> Send build pipeline information to Telemetry

- src/BinaryParsers/BinaryBase.cs
- src/BinaryParsers/IBinary.cs
- src/BinaryParsers/MachOBinary/MachOCompiler.cs
- src/BinaryParsers/PlatformSpecificHelpers.cs
Removed unneeded using statement and code cleanup
> Code cleanup

- .github/workflows/codeql-analysis.yml
Enabling CodeQL to run on all branches
Updating cron to run only once a week
> Update CodeQL analysis to run on all branches and on Sunday (cron)

- .github/workflows/codeql-analysis.yml
- src/BinSkim.sln
The codeQL yml file had a type mismatch. Added this file and others in the folder to solution items to aid in adhering to team standard for validating file changes in the IDE.
> codeQL fixes

- src/BinSkim.Sdk/BinaryAnalyzerContext.cs
- src/BinSkim.Sdk/CompilerDataLogger.cs
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTests.cs
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTests.runsettings
- src/Test.FunctionalTests.BinSkim.Driver/Test.FunctionalTests.BinSkim.Driver.csproj
- src/Test.UnitTests.BinSkim.Driver/CompilerDataLoggerTests.cs
Added unit tests for compiler telemetry methods and functional tests for compiler telemetry generation.
> Adding test cases for Compiler Telemetry Events

- src/BinSkim.Driver/BinSkim.Driver.csproj
- src/BinSkim.Rules/BinSkim.Rules.csproj
- src/BinSkim.Sdk/BinSkim.Sdk.csproj
- src/BinSkim.Sdk/CompilerDataLogger.cs
- src/BinaryParsers/BinaryParsers.csproj
- src/BinaryParsers/VersionConstants.cs
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTests.cs
- src/Test.FunctionalTests.BinSkim.Driver/Test.FunctionalTests.BinSkim.Driver.csproj
- src/Test.FunctionalTests.BinSkim.Rules/Test.FunctionalTests.BinSkim.Rules.csproj
- src/Test.UnitTests.BinSkim.Driver/CompilerDataLoggerTests.cs
- src/Test.UnitTests.BinSkim.Driver/Test.UnitTests.BinSkim.Driver.csproj
- src/Test.UnitTests.BinSkim.Rules/Test.UnitTests.BinSkim.Rules.csproj
- src/Test.UnitTests.BinaryParsers/Test.UnitTests.BinaryParsers.csproj
- src/build.common.props
@shaopeng-gh @yongyan-gh @suvamM @EasyRhinoMSFT @eddynaka @LingZhou-gh 
Moving quickly, hoping to get a review soon. :)
> Update all dependencies to latest except for command line parser.

- ReleaseHistory.md
- docs/UserGuide.md
- src/BinSkim.Driver/MultithreadedAnalyzeCommand.cs
- src/BinSkim.sln
Please make sure to review the code change inside `CreateContext` to `CreateScanTargetContext` which I am not as confident.
> Fix merge build error

- src/BinSkim.Driver/MultithreadedAnalyzeCommand.cs
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTestData/Expected/clangcl.pe.cpp.codeview.exe.sarif
1. Fix the MaxFileSizeInKilobytes change not effective
2. Update baseline
> Fix the MaxFileSizeInKilobytes change not effective

- ReleaseHistory.md
- src/BinSkim.Rules/PERules/BA4001.ReportPortableExecutableCompilerData.cs
- src/BinSkim.Sdk/CompilerData.cs
- src/BinSkim.Sdk/CompilerDataLogger.cs
Adding last modified date for scan targets. Tested via App Insights.
> Adding last mod date for targets

- ReleaseHistory.md
- src/BinSkim.Rules/PERules/BA2004.EnableSecureSourceCodeHashing.cs
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTestData/Expected/MixedMode_x64_VS2013_Default.dll.sarif
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTestData/Expected/MixedMode_x64_VS2015_Default.exe.sarif
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTestData/Expected/MixedMode_x64_VS2019_CPlusPlus_DEBUG_DEFAULT.dll.sarif
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTestData/Expected/MixedMode_x64_VS2019_CPlusPlus_DEBUG_FASTLINK.dll.sarif
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTestData/Expected/MixedMode_x64_VS2019_CPlusPlus_DEBUG_FULL.dll.sarif
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTestData/Expected/MixedMode_x86_VS2013_Default.exe.sarif
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTestData/Expected/MixedMode_x86_VS2015_Default.exe.sarif
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTestData/Expected/Native_x64_VS2013_Default.dll.sarif
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTestData/Expected/Native_x64_VS2015_Default.dll.sarif
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTestData/Expected/Native_x86_VS2013_Default.exe.sarif
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTestData/Expected/Native_x86_VS2015_Default.exe.sarif
- src/Test.FunctionalTests.BinSkim.Driver/BaselineTestData/Expected/Native_x86_VS2015_Default_Debug.dll.sarif
Please see https://github.com/microsoft/binskim/issues/974
And please see the comments I added in the test output file in the PR.
> Exclude system generated files from `BA2004.EnableSecureSourceCodeHashing`.

- ReleaseHistory.md
- ado-build.yml
- src/BinaryParsers/ElfBinary/Dwarf/DwarfAttributeValue.cs
- src/BinaryParsers/ElfBinary/Dwarf/DwarfCommonInformationEntry.cs
- src/BinaryParsers/ElfBinary/Dwarf/DwarfCompilationUnit.cs
- src/BinaryParsers/ElfBinary/Dwarf/DwarfFrameDescriptionEntry.cs
- src/BinaryParsers/ElfBinary/Dwarf/DwarfLineNumberProgram.cs
- src/BinaryParsers/ElfBinary/Dwarf/DwarfMemoryReader.cs
- src/BinaryParsers/ElfBinary/Dwarf/DwarfSymbol.cs
- src/BinaryParsers/ElfBinary/Dwarf/DwarfSymbolProvider.cs
- src/BinaryParsers/ElfBinary/ElfBinary.cs
- src/Test.UnitTests.BinaryParsers/Elf/ElfBinaryTests.cs
change data type for bigger in order to read dwarf5 format
> fixing dwarf5 binaries pointers from int to uint

- ReleaseHistory.md
- src/BinSkim.Driver/BinSkim.Driver.csproj
Update destination folder for MsDiaLib, after MsDiaLib update
> Update destination folder for MsDiaLib
